name: Deploy

on:
  workflow_dispatch:
    inputs:
      deployImage:
        type: string
        required: true
        description: Image to deploy
      environment:
        type: environment
        required: true
        description: ENV to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environement }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: deploy
        run: |
          echo "Deploying ${{ github.event.inputs.deployImage }} to ${{ github.event.inputs.environment }}"
          sleep 60
        id: deploy

