name: Test Exptessions

run-name: Test Exptessions

on:
  workflow_dispatch:
    inputs:
      is_snapshot:
        type: boolean
        description: Is it a snapshot build
        default: true

env:
  env: DEV
  VERSION_PREFIX: >-
    ${{
      inputs.is_snapshot == 'true' && 'SNAPSHOT' ||
      '' 
    }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo ${GITHUB_CONTEXT} | jq .
    - name: Version prefix
      run: echo "version prefix is ${VERSION_PREFIX}"
    - name: Format
      run: |
        echo ${{ format('{1}: {0} tiggered run on {1}.', github.actor, env.env) }}
