name: Test Exptessions

run-name: Test Exptessions

on:
  workflow_dispatch: {}

env:
  env: DEV

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Format
      run: |
        echo ${{ format('{1}: {0} tiggered run on {1}.', github.actor, env.env) }}
