name: Build
permissions:
  actions: write
on:
  workflow_dispatch: {}
  pull_reqests:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: build
        run: echo "image=nginx:1.26" >> $GITHUB_OUTPUT
        id: build
      - name: Trigger deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "${{ github.repository_owner }}",
              repo: 'deploy-repo',
              workflow_id: 'manual.yaml',
              ref: 'main',
              inputs: {
                deployImage: "${{ steps.build.outputs.image }}"
              },
            })
