name: Build

on:
  workflow_dispatch: {}
#  pull_request:
#    types:
#      - opened
#      - synchronize
#      - reopened
#      - closed
#    branches:
#      - main
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: env
      - name: build
        run: echo "image=nginx:1.26" >> $GITHUB_OUTPUT
        id: build
#      - name: Trigger deploy
#        env:
#          GH_TOKEN: ${{ github.token }}
#        run: |
#          gh workflow run \
#            --ref 'main' \
#            --repo 'ilakhtenkov/deploy-repo' \
#            --field 'deployImage=nginx:1.26' \
#            manual.yaml
      - name: Trigger deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "${{ github.repository_owner }}",
              repo: 'build-repo',
              workflow_id: 'deploy.yaml',
              ref: 'main',
              inputs: {
                deployImage: "${{ steps.build.outputs.image }}",
                environment: 'prd'
              },
            })
