name: Build
permissions:
  actions: write
on:
  workflow_dispatch:
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "::set-output name=image::nginx:1.26"
        id: build
      - name: Trigger deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "${{ github.repository_owner }}",
              repo: 'deploy-repo',
              workflow_id: 'manual.yaml',
              ref: 'main',
              inputs: {
                deployImage: "${{ steps.build.outputs.image }}"
              },
            })