name: Test workflow
permissions:
  actions: write
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
      - id: step3
        run: echo "test=top_secret" >> $GITHUB_ENV
      - id: step4
        run: |
          echo ${{steps.step1.outputs.test}} ${{steps.step2.outputs.test}}
          echo ${{env.test}}