name: Test workflow

run-name: >-
  ${{ github.event.inputs.env }}
  ${{ github.event.inputs.config != '' && format('| {0}', github.event.inputs.config) || '' }}

env:
  ENV: ${{ github.event.inputs.env }}
  BUCKET: ${{ github.event.inputs.env }}_bucket

permissions:
  actions: write
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: choice
        options: 
          - dev
          - stg
          - prd
        default: dev
        required: true
      config:
        description: "Config to deploy"
        type: string
        required: false
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          echo "ENV: ${ENV}, BUCKET: ${BUCKET}"
          echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
      - id: step3
        run: echo "test=top_secret" >> $GITHUB_ENV
      - id: step4
        run: |
          echo ${{steps.step1.outputs.test}} ${{steps.step2.outputs.test}}
          echo ${{env.test}}
