name: On New Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run your build or deployment steps here
        # Replace this with your actual build or deployment steps
        run: |
          echo "New tag pushed: ${{ github.ref }}"
          # Add your build or deployment commands here